In [46]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [56]:
df1 = pd.read_csv('spam.csv',encoding='latin#1')

In [50]:
df1

                                            Document  Class
0         Teclov is a great educational institution.    1.0
1            Educational greatness depends on ethics    1.0
2  A story of great ethics and educational greatness    1.0
3                           Sholey is a great cinema    NaN
4                   good movie depends on good story    NaN

In [75]:
df1['v1'] = df1.v2.map({'ham':0, 'spam':1})
df1

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4,Class
0,NaN,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,NaN
1,NaN,Ok lar... Joking wif u oni...,NaN,NaN,NaN,NaN
2,NaN,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,NaN
3,NaN,U dun say so early hor... U c already then say...,NaN,NaN,NaN,NaN
4,NaN,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
5567,NaN,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN,NaN
5568,NaN,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN,NaN
5569,NaN,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN,NaN
5570,NaN,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN,NaN
5571,NaN,Rofl. Its true to its name,NaN,NaN,NaN,NaN

In [76]:
X= df1['v2'].to_numpy()
Y = df1['v1'].to_numpy()
Y = Y.astype('int')

In [77]:
print("X")
print(X)
print("Y")
print(Y)

X
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
Y
[-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
 -9223372036854775808 -9223372036854775808 -9223372036854775808]

In [78]:
vec = CountVectorizer( )

In [80]:
vec = CountVectorizer(stop_words='english' )
vec.fit(X)
vec.vocabulary_

{'jurong': 4224,
 'point': 5741,
 'crazy': 2271,
 'available': 1271,
 'bugis': 1703,
 'great': 3534,
 'world': 8227,
 'la': 4349,
 'buffet': 1701,
 'cine': 1994,
 'got': 3494,
 'amore': 1051,
 'wat': 8026,
 'ok': 5343,
 'lar': 4385,
 'joking': 4192,
 'wif': 8134,
 'oni': 5369,
 'free': 3265,
 'entry': 2875,
 'wkly': 8185,
 'comp': 2110,
 'win': 8146,
 'fa': 3005,
 'cup': 2329,
 'final': 3121,
 'tkts': 7519,
 '21st': 411,
 '2005': 402,
 'text': 7388,
 '87121': 784,
 'receive': 6115,
 'question': 6010,
 'std': 7028,
 'txt': 7701,
 'rate': 6062,
 'apply': 1128,
 '08452810075over18': 77,
 'dun': 2738,
 'say': 6450,
 'early': 2757,
 'hor': 3815,
 'nah': 5092,
 'don': 2651,
 'think': 7443,
 'goes': 3458,
 'usf': 7837,
 'lives': 4535,
 'freemsg': 3272,
 'hey': 3732,
 'darling': 2386,
 'week': 8071,
 'word': 8218,
 'like': 4485,
 'fun': 3323,
 'tb': 7323,
 'xxx': 8292,
 'chgs': 1948,
 'send': 6536,
 '50': 607,
 'rcv': 6074,
 'brother': 1674,
 'speak': 6910,
 'treat': 7634,
 'aids': 985,
 'patent': 5546,
 'request': 6224,
 'melle': 4833,
 'oru': 5426,
 'minnaminunginte': 4898,
 'nurungu': 5282,
 'vettam': 7892,
 'set': 6562,
 'callertune': 1772,
 'callers': 1771,
 'press': 5862,
 'copy': 2211,
 'friends': 3288,
 'winner': 8157,
 'valued': 7862,
 'network': 5169,
 'customer': 2342,
 'selected': 6522,
 'receivea': 6116,
 '900': 816,
 'prize': 5894,
 'reward': 6279,
 'claim': 2000,
 '09061701461': 224,
 'code': 2065,
 'kl341': 4312,
 'valid': 7858,
 '12': 322,
 'hours': 3835,
 'mobile': 4951,
 '11': 312,
 'months': 4991,
 'entitled': 2872,
 'update': 7801,
 'latest': 4398,
 'colour': 2086,
 'mobiles': 4952,
 'camera': 1784,
 '08002986030': 61,
 'gonna': 3474,
 'home': 3789,
 'soon': 6864,
 'want': 8005,
 'talk': 7290,
 'stuff': 7117,
 'anymore': 1099,
 'tonight': 7566,
 've': 7877,
 'cried': 2288,
 'today': 7538,
 'chances': 1889,
 'cash': 1835,
 '100': 298,
 '20': 397,
 '000': 1,
 'pounds': 5803,
 'csh11': 2306,
 '87575': 789,
 'cost': 2223,
 '150p': 351,
 'day': 2401,
 '6days': 680,
 '16': 363,
 'tsandcs': 7669,
 'reply': 6217,
 'hl': 3761,
 'info': 4002,
 'urgent': 7818,
 'won': 8202,
 'membership': 4839,
 'jackpot': 4121,
 '81010': 737,
 'www': 8274,
 'dbuk': 2406,
 'net': 5163,
 'lccltd': 4415,
 'pobox': 5720,
 '4403ldnw1a7rw18': 559,
 'searching': 6495,
 'right': 6291,
 'words': 8219,
 'thank': 7404,
 'breather': 1643,
 'promise': 5926,
 'wont': 8209,
 'help': 3712,
 'granted': 3523,
 'fulfil': 3320,
 'wonderful': 8206,
 'blessing': 1521,
 'times': 7498,
 'date': 2394,
 'sunday': 7184,
 'xxxmobilemovieclub': 8293,
 'use': 7831,
 'credit': 2278,
 'click': 2023,
 'wap': 8010,
 'link': 4507,
 'message': 4857,
 'http': 3854,
 'com': 2089,
 'qjkgighjjgcbl': 6002,
 'oh': 5338,
 'watching': 8031,
 'eh': 2803,
 'remember': 6184,
 'spell': 6925,
 'yes': 8329,
 'did': 2532,
 'naughty': 5124,
 'make': 4716,
 'wet': 8106,
 'fine': 3128,
 'thatåõs': 7416,
 'way': 8043,
 'feel': 3076,
 'gota': 3495,
 'england': 2854,
 'macedonia': 4679,
 'dont': 2654,
 'miss': 4914,
 'goals': 3454,
 'team': 7335,
 'news': 5181,
 'ur': 7814,
 'national': 5118,
 '87077': 783,
 'try': 7665,
 'wales': 7985,
 'scotland': 6474,
 '4txt': 599,
 'ì¼1': 8391,
 'poboxox36504w45wq': 5732,
 'seriously': 6555,
 'going': 3463,
 'ha': 3595,
 'ì_': 8390,
 'pay': 5558,
 'da': 2359,
 'stock': 7053,
 'comin': 2100,
 'aft': 959,
 'finish': 3131,
 'lunch': 4645,
 'str': 7078,
 'lor': 4589,
 'ard': 1154,
 'smth': 6812,
 'ffffffffff': 3094,
 'alright': 1031,
 'meet': 4822,
 'sooner': 6865,
 'just': 4226,
 'forced': 3219,
 'eat': 2769,
 'slice': 6764,
 'really': 6098,
 'hungry': 3873,
 'tho': 7458,
 'sucks': 7153,
 'mark': 4752,
 'getting': 3413,
 'worried': 8230,
 'knows': 4323,
 'sick': 6685,
 'turn': 7688,
 'pizza': 5676,
 'lol': 4566,
 'convincing': 2199,
 'catch': 1845,
 'bus': 1723,
 'frying': 3308,
 'egg': 2800,
 'tea': 7329,
 'eating': 2772,
 'mom': 4972,
 'left': 4437,
 'dinner': 2564,
 'love': 4610,
 'amp': 1052,
 'packing': 5478,
 'car': 1807,
 'll': 4539,
 'let': 4457,
 'know': 4320,
 'room': 6332,
 'ahhh': 980,
 'work': 8220,
 'vaguely': 7854,
 'does': 2626,
 'wait': 7979,
 'clear': 2017,
 'sure': 7210,
 'sarcastic': 6430,
 'doesn': 2628,
 'live': 4531,
 'yeah': 8317,
 'apologetic': 1115,
 'fallen': 3030,
 'actin': 901,
 'spoilt': 6952,
 'child': 1956,
 'caught': 1849,
 'till': 7495,
 'doing': 2641,
 'badly': 1323,
 'cheers': 1932,
 'tell': 7353,
 'fear': 3068,
 'fainting': 3022,
 'housework': 3839,
 'quick': 6013,
 'cuppa': 2331,
 'thanks': 7405,
 'subscription': 7142,
 'ringtone': 6300,
 'uk': 7731,
 'charged': 1901,
 'month': 4988,
 'confirm': 2154,
 'replying': 6218,
 'yup': 8369,
 'look': 4577,
 'timings': 7502,
 'msg': 5026,
 'xuhui': 8288,
 'learn': 4428,
 '2nd': 461,
 'lesson': 4455,
 '8am': 809,
 'oops': 5382,
 'roommate': 6334,
 'letter': 4459,
 'decide': 2423,
 'hello': 3709,
 'saturday': 6442,
 'texting': 7396,
 'decided': 2424,
 'tomo': 7555,
 'trying': 7667,
 'invite': 4058,
 'pls': 5708,
 'ahead': 979,
 'watts': 8039,
 'wanted': 8007,
 'weekend': 8073,
 'abiola': 855,
 'forget': 3225,
 'need': 5144,
 'crave': 2268,
 'sweet': 7241,
 'arabian': 1151,
 'steed': 7035,
 'mmmmmm': 4941,
 'yummy': 8364,
 '07732584351': 30,
 'rodger': 6322,
 'burns': 1720,
 'tried': 7643,
 'sms': 6807,
 'nokia': 5225,
 'camcorder': 1782,
 '08000930705': 57,
 'delivery': 2463,
 'tomorrow': 7557,
 'seeing': 6513,
 'hope': 3807,
 'man': 4726,
 'endowed': 2844,
 'lt': 4633,
 'gt': 3563,
 'inches': 3972,
 'calls': 1777,
 'messages': 4859,
 'missed': 4916,
 'didn': 2534,
 'hep': 3723,
 'immunisation': 3953,
 'nigeria': 5194,
 'fair': 3023,
 'hopefully': 3810,
 'tyler': 7714,
 'maybe': 4798,
 'ask': 1203,
 'bit': 1498,
 'stubborn': 7106,
 'hospital': 3822,
 'kept': 4269,
 'telling': 7354,
 'weak': 8048,
 'sucker': 7151,
 'hospitals': 3823,
 'suckers': 7152,
 'thinked': 7444,
 'time': 7497,
 'saw': 6449,
 'class': 2009,
 'gram': 3515,
 'usually': 7843,
 'runs': 6375,
 'half': 3610,
 'eighth': 2805,
 'smarter': 6787,
 'gets': 3409,
 'second': 6499,
 'fyi': 3338,
 'ride': 6290,
 'morning': 4998,
 'crashing': 2267,
 'place': 5678,
 'wow': 8245,
 'realized': 6096,
 'embarassed': 2826,
 'accomodations': 884,
 'thought': 7461,
 'liked': 4486,
 'best': 1455,
 'happy': 3645,
 'cave': 1853,
 'sorry': 6874,
 'offered': 5324,
 'embarassing': 2827,
 'ac': 870,
 'sptv': 6974,
 'new': 5176,
 'jersey': 4162,
 'devils': 2513,
 'detroit': 2507,
 'red': 6138,
 'wings': 8155,
 'play': 5692,
 'ice': 3907,
 'hockey': 3774,
 'correct': 2216,
 'incorrect': 3983,
 'end': 2840,
 'mallika': 4725,
 'sherawat': 6612,
 'yesterday': 8331,
 'url': 7824,
 'congrats': 2160,
 'year': 8318,
 'special': 6912,
 'cinema': 1995,
 'pass': 5535,
 '09061209465': 219,
 'suprman': 7208,
 'matrix3': 4785,
 'starwars3': 7016,
 'bx420': 1743,
 'ip4': 4067,
 '5we': 641,
 '150pm': 353,
 'later': 4397,
 'meeting': 4824,
 'reached': 6080,
 'gauti': 3372,
 'sehwag': 6519,
 'odi': 5318,
 'series': 6554,
 'pick': 5648,
 'burger': 1715,
 'pain': 5485,
 'killing': 4294,
 'good': 3476,
 'joke': 4188,
 'girls': 3431,
 'situation': 6731,
 'seekers': 6514,
 'checking': 1926,
 'iq': 4073,
 'roommates': 6335,
 'took': 7570,
 'forever': 3222,
 'come': 2095,
 'double': 2668,
 'check': 1922,
 'hair': 3605,
 'dresser': 2697,
 'said': 6401,
 'wun': 8273,
 'cut': 2346,
 'short': 6647,
 'nice': 5188,
 'pleased': 5701,
 'advise': 942,
 'following': 3201,
 'recent': 6119,
 'review': 6277,
 'mob': 4949,
 'awarded': 1288,
 '1500': 350,
 'bonus': 1562,
 '09066364589': 267,
 'song': 6859,
 'dedicated': 2434,
 'dedicate': 2433,
 'valuable': 7860,
 'frnds': 3296,
 'rply': 6351,
 'complimentary': 2129,
 'trip': 7644,
 'eurodisinc': 2917,
 'trav': 7626,
 'aco': 898,
 'entry41': 2876,
 '1000': 299,
 'dis': 2576,
 '18': 368,
 'morefrmmob': 4995,
 'shracomorsglsuplt': 6670,
 '10': 297,
 'ls1': 4629,
 '3aj': 518,
 'hear': 3688,
 'divorce': 2605,
 'barbie': 1354,
 'comes': 2097,
 'ken': 4267,
 'plane': 5684,
 'wah': 7972,
 'lucky': 4639,
 'save': 6445,
 'money': 4979,
 'hee': 3701,
 'finished': 3133,
 'hi': 3737,
 'babe': 1310,
 'im': 3941,
 'wanna': 8003,
 'xx': 8289,
 'performed': 5594,
 'waiting': 7982,
 'machan': 4681,
 'thats': 7415,
 'cool': 2204,
 'gentleman': 3397,
 'dignity': 2554,
 'respect': 6244,
 'peoples': 5587,
 'shy': 6680,
 'pa': 5474,
 'operate': 5389,
 'looking': 4581,
 'job': 4177,
 'ta': 7268,
 'earn': 2758,
 'ah': 977,
 'stop': 7063,
 'urgnt': 7821,
 'real': 6089,
 'yo': 8340,
 'tickets': 7485,
 'jacket': 4120,
 'used': 7832,
 'multis': 5052,
 'started': 7011,
 'requests': 6225,
 'came': 1783,
 'bed': 1418,
 'coins': 2071,
 'factory': 3012,
 'gotta': 3500,
 'nitros': 5212,
 'ela': 2809,
 'kano': 4249,
 'il': 3936,
 'download': 2675,
 'wen': 8090,
 'stand': 6999,
 'close': 2030,
 'night': 5196,
 'spent': 6930,
 'late': 4394,
 'afternoon': 961,
 'casualty': 1843,
 'means': 4811,
 'haven': 3667,
 'stuff42moro': 7118,
 'includes': 3976,
 'sheets': 6607,
 'smile': 6795,
 'pleasure': 5703,
 'trouble': 7651,
 'pours': 5805,
 'rain': 6036,
 'sum1': 7175,
 'hurts': 3883,
 'becoz': 1416,
 'loves': 4618,
 'smiling': 6799,
 'service': 6558,
 'representative': 6222,
 '0800': 53,
 '169': 366,
 '6031': 647,
 '10am': 307,
 '9pm': 835,
 'guaranteed': 3566,
 '5000': 609,
 'havent': 3668,
 'planning': 5688,
 'buy': 1734,
 'lido': 4470,
 '530': 627,
 'collected': 2080,
 'simply': 6706,
 'password': 5542,
 'mix': 4932,
 '85069': 770,
 'verify': 7888,
 'usher': 7838,
 'britney': 1664,
 'fml': 3192,
 'telugu': 7359,
 'movie': 5015,
 'abt': 865,
 'loads': 4545,
 'loans': 4547,
 'wk': 8181,
 'hols': 3787,
 'run': 6373,
 'forgot': 3230,
 'hairdressers': 3607,
 'appointment': 1131,
 'shower': 6663,
 'cause': 1850,
 'prob': 5899,
 'ham': 3616,
 'okay': 5344,
 'price': 5875,
 'long': 4573,
 'legal': 4440,
 'ave': 1275,
 'ams': 1056,
 'gone': 3472,
 '4the': 597,
 'driving': 2706,
 'test': 7382,
 'mean': 4807,
 'guess': 3572,
 'gave': 3373,
 'boston': 1583,
 'men': 4843,
 'changed': 1891,
 'search': 6494,
 'location': 4550,
 'nyc': 5293,
 'cuz': 2353,
 'signin': 6694,
 'page': 5481,
 'says': 6453,
 'umma': 7738,
 'life': 4473,
 'vava': 7874,
 'lot': 4597,
 'dear': 2413,
 'wishes': 8168,
 'birthday': 1496,
 'making': 4720,
 'truly': 7660,
 'memorable': 4840,
 'aight': 987,
 'hit': 3754,
 'ip': 4066,
 'address': 919,
 'considering': 2172,
 'computer': 2135,
 'isn': 4090,
 'minecraft': 4892,
 'server': 6557,
 'grumpy': 3560,
 'old': 5356,
 'people': 5586,
 'better': 1461,
 'lying': 4659,
 'jokes': 4190,
 'worry': 8232,
 'busy': 1729,
 'plural': 5712,
 'noun': 5261,
 'research': 6230,
 'cos': 2221,
 'things': 7442,
 'scared': 6459,
 'mah': 4703,
 'loud': 4605,
 'gent': 3395,
 'contact': 2177,
 'weekends': 8074,
 'draw': 2689,
 'shows': 6669,
 '09064012160': 243,
 'k52': 4232,
 '12hrs': 333,
 '150ppm': 355,
 'wa': 7967,
 'openin': 5386,
 'sentence': 6547,
 'formal': 3234,
 'juz': 4231,
 'tt': 7675,
 'eatin': 2771,
 'puttin': 5991,
 'weight': 8079,
 'haha': 3601,
 'anythin': 1103,
 'happened': 3637,
 'entered': 2865,
 'cabin': 1751,
 'boss': 1582,
 'felt': 3085,
 'askd': 1204,
 'invited': 4059,
 'apartment': 1109,
 'went': 8093,
 'specially': 6916,
 'holiday': 3784,
 'flights': 3168,
 'operator': 5390,
 '0871277810910p': 129,
 'min': 4886,
 'goodo': 3485,
 'friday': 3283,
 'potato': 5797,
 'ratio': 6064,
 'tortilla': 7586,
 'needed': 5146,
 'hmm': 3766,
 'uncle': 7746,
 'informed': 4005,
 'paying': 5563,
 'school': 6465,
 'directly': 2570,
 'food': 3208,
 'private': 5891,
 '2004': 401,
 'account': 887,
 'statement': 7019,
 '07742676969': 32,
 '786': 709,
 'unredeemed': 7789,
 'points': 5742,
 '08719180248': 175,
 'identifier': 3919,
 '45239': 570,
 'expires': 2983,
 '2000': 399,
 'caller': 1770,
 '03': 15,
 'landline': 4372,
 '09064019788': 249,
 'box42wr29c': 1607,
 'apples': 1126,
 'pairs': 5489,
 'malarky': 4722,
 'todays': 7539,
 'voda': 7936,
 'numbers': 5279,
 'ending': 2842,
 '7548': 701,
 '350': 506,
 'award': 1287,
 'match': 4773,
 '08712300220': 111,
 'quoting': 6024,
 '4041': 543,
 'standard': 7000,
 'rates': 6063,
 'app': 1119,
 'sao': 6424,
 'mu': 5042,
 'ìï': 8393,
 'predict': 5837,
 'buying': 1737,
 'yetunde': 8333,
 'hasn': 3657,
 'sent': 6546,
 'bother': 1585,
 'sending': 6538,
 'involve': 4063,
 'shouldn': 6657,
 'imposed': 3960,
 'apologise': 1116,
 'girl': 3428,
 'del': 2453,
 'bak': 1331,
 'sum': 7174,
 'lucyxx': 4642,
 'tmorrow': 7525,
 'accomodate': 883,
 'answer': 1087,
 'sunshine': 7191,
 'quiz': 6020,
 'sony': 6861,
 'dvd': 2747,
 'player': 5694,
 'country': 2240,
 'algarve': 1015,
 'ansr': 1086,
 '82277': 744,
 'sp': 6897,
 'tyrone': 7718,
 'laid': 4364,
 'dogging': 2635,
 'locations': 4551,
 'direct': 2569,
 'join': 4185,
 'largest': 4389,
 'bt': 1690,
 'txting': 7707,
 'gravel': 3528,
 '69888': 675,
 'nt': 5269,
 'ec2a': 2774,
 '31p': 498,
 'haf': 3600,
 'msn': 5033,
 'yijue': 8337,
 'hotmail': 3830,
 'rooms': 6336,
 'befor': 1427,
 'activities': 907,
 'msgs': 5032,
 'chat': 1912,
 'svc': 7226,
 'hardcore': 3647,
 'services': 6559,
 '69988': 679,
 'age': 966,
 'yr': 8359,
 'lazy': 4414,
 'type': 7715,
 'lect': 4434,
 'pouch': 5800,
 'sir': 6720,
 'mail': 4708,
 'swt': 7255,
 'nver': 5287,
 'tired': 7505,
 'little': 4530,
 'lovable': 4609,
 'persons': 5611,
 'coz': 2253,
 'somtimes': 6856,
 'occupy': 5311,
 'biggest': 1479,
 'hearts': 3694,
 'gud': 3568,
 'ni8': 5186,
 'open': 5383,
 'ya': 8302,
 'dot': 2667,
 'whats': 8111,
 'staff': 6991,
 'taking': 7287,
 'replied': 6215,
 'randy': 6056,
 'sexy': 6574,
 'female': 3086,
 'local': 4549,
 'luv': 4650,
 'netcollex': 5164,
 '08700621170150p': 81,
 'ummma': 7740,
 'begin': 1431,
 'qatar': 5997,
 'pray': 5832,
 'hard': 3646,
 'deleted': 2457,
 'sindu': 6710,
 'birla': 1492,
 'soft': 6833,
 'wine': 8153,
 'flowing': 3183,
 'nevering': 5173,
 'thk': 7452,
 'plaza': 5699,
 'typical': 7717,
 'dirt': 2573,
 'floor': 3177,
 'windows': 8150,
 'shirt': 6626,
 'mouth': 5012,
 'dream': 2692,
 'chores': 1983,
 'joy': 4203,
 'lots': 4599,
 'tv': 7693,
 'exist': 2968,
 'hail': 3604,
 'mist': 4924,
 'aaooooright': 845,
 'leaving': 4433,
 'house': 3836,
 'interview': 4046,
 'boy': 1612,
 'missing': 4918,
 'annoncement': 1078,
 'years': 8319,
 '07046744435': 24,
 'arrange': 1180,
 '0871277810810': 128,
 'safe': 6396,
 'envy': 2881,
 'parents': 5518,
 'hand': 3619,
 'excited': 2956,
 'spend': 6928,
 'bootydelious': 1575,
 '32': 499,
 'inviting': 4060,
 'friend': 3287,
 '434': 556,
 'frnd': 3295,
 '62468': 655,
 'bangbabes': 1345,
 'order': 5411,
 'content': 2181,
 'goto': 3499,
 'bangb': 1344,
 'internet': 4045,
 'menu': 4850,
 'cultures': 2325,
 'module': 4965,
 '09061701939': 226,
 's89': 6386,
 'avoid': 1281,
 'missunderstding': 4922,
 'wit': 8173,
 'beloved': 1446,
 'escape': 2902,
 'fancy': 3041,
 'bridge': 1649,
 'needs': 5149,
 'lager': 4363,
 'completely': 2125,
 'form': 3233,
 'clark': 2006,
 'utter': 7845,
 'waste': 8023,
 'axis': 1296,
 'bank': 1347,
 'hmmm': 3767,
 'hop': 3806,
 'muz': 5076,
 'discuss': 2589,
 'liao': 4464,
 'coming': 2101,
 'bloody': 1535,
 'hell': 3707,
 'believe': 1437,
 'surname': 7216,
 'mr': 5021,
 'ill': 3938,
 'clue': 2046,
 'spanish': 6904,
 'begins': 1432,
 'bath': 1378,
 'carlos': 1824,
 'mall': 4724,
 'turns': 7691,
 'staying': 7026,
 'til': 7494,
 'smoke': 6801,
 'worth': 8236,
 'doesnt': 2629,
 'log': 4557,
 'spoke': 6953,
 'maneesha': 4736,
 'satisfied': 6439,
 'experience': 2978,
 'toll': 7551,
 'lifted': 4479,
 'hopes': 3812,
 'offer': 5323,
 'especially': 2906,
 'approaches': 1135,
 'studying': 7115,
 'anyways': 1106,
 'gr8': 3508,
 'trust': 7662,
 'guys': 3588,
 'bye': 1746,
 'handsome': 3625,
 'finding': 3126,
 'working': 8224,
 'mummy': 5056,
 'boytoy': 1617,
 'awesome': 1290,
 'minute': 4903,
 'freephone': 3273,
 '0808': 65,
 '145': 343,
 '4742': 574,
 '9am': 833,
 '11pm': 321,
 'xmas': 8285,
 'radio': 6029,
 'jus': 4225,
 'bathe': 1379,
 'sis': 6722,
 'using': 7839,
 'finishes': 3134,
 'unique': 7774,
 '30th': 494,
 'august': 1257,
 'areyouunique': 1160,
 'joined': 4186,
 'league': 4426,
 'touch': 7595,
 'deal': 2409,
 'personal': 5608,
 'finally': 3123,
 'completed': 2124,
 'course': 2246,
 'suggest': 7166,
 'stays': 7027,
 'able': 857,
 'ors': 5424,
 'stool': 7062,
 'settled': 6566,
 'wishin': 8169,
 'mrng': 5023,
 'hav': 3665,
 'story': 7077,
 'hamster': 3618,
 'dead': 2408,
 'tmr': 7526,
 '1pm': 385,
 'orchard': 5410,
 'mrt': 5024,
 'kate': 4254,
 'evening': 2923,
 ...}

In [81]:
vec = CountVectorizer(stop_words='english' )
vec.fit(X)
vec.vocabulary_

{'jurong': 4224,
 'point': 5741,
 'crazy': 2271,
 'available': 1271,
 'bugis': 1703,
 'great': 3534,
 'world': 8227,
 'la': 4349,
 'buffet': 1701,
 'cine': 1994,
 'got': 3494,
 'amore': 1051,
 'wat': 8026,
 'ok': 5343,
 'lar': 4385,
 'joking': 4192,
 'wif': 8134,
 'oni': 5369,
 'free': 3265,
 'entry': 2875,
 'wkly': 8185,
 'comp': 2110,
 'win': 8146,
 'fa': 3005,
 'cup': 2329,
 'final': 3121,
 'tkts': 7519,
 '21st': 411,
 '2005': 402,
 'text': 7388,
 '87121': 784,
 'receive': 6115,
 'question': 6010,
 'std': 7028,
 'txt': 7701,
 'rate': 6062,
 'apply': 1128,
 '08452810075over18': 77,
 'dun': 2738,
 'say': 6450,
 'early': 2757,
 'hor': 3815,
 'nah': 5092,
 'don': 2651,
 'think': 7443,
 'goes': 3458,
 'usf': 7837,
 'lives': 4535,
 'freemsg': 3272,
 'hey': 3732,
 'darling': 2386,
 'week': 8071,
 'word': 8218,
 'like': 4485,
 'fun': 3323,
 'tb': 7323,
 'xxx': 8292,
 'chgs': 1948,
 'send': 6536,
 '50': 607,
 'rcv': 6074,
 'brother': 1674,
 'speak': 6910,
 'treat': 7634,
 'aids': 985,
 'patent': 5546,
 'request': 6224,
 'melle': 4833,
 'oru': 5426,
 'minnaminunginte': 4898,
 'nurungu': 5282,
 'vettam': 7892,
 'set': 6562,
 'callertune': 1772,
 'callers': 1771,
 'press': 5862,
 'copy': 2211,
 'friends': 3288,
 'winner': 8157,
 'valued': 7862,
 'network': 5169,
 'customer': 2342,
 'selected': 6522,
 'receivea': 6116,
 '900': 816,
 'prize': 5894,
 'reward': 6279,
 'claim': 2000,
 '09061701461': 224,
 'code': 2065,
 'kl341': 4312,
 'valid': 7858,
 '12': 322,
 'hours': 3835,
 'mobile': 4951,
 '11': 312,
 'months': 4991,
 'entitled': 2872,
 'update': 7801,
 'latest': 4398,
 'colour': 2086,
 'mobiles': 4952,
 'camera': 1784,
 '08002986030': 61,
 'gonna': 3474,
 'home': 3789,
 'soon': 6864,
 'want': 8005,
 'talk': 7290,
 'stuff': 7117,
 'anymore': 1099,
 'tonight': 7566,
 've': 7877,
 'cried': 2288,
 'today': 7538,
 'chances': 1889,
 'cash': 1835,
 '100': 298,
 '20': 397,
 '000': 1,
 'pounds': 5803,
 'csh11': 2306,
 '87575': 789,
 'cost': 2223,
 '150p': 351,
 'day': 2401,
 '6days': 680,
 '16': 363,
 'tsandcs': 7669,
 'reply': 6217,
 'hl': 3761,
 'info': 4002,
 'urgent': 7818,
 'won': 8202,
 'membership': 4839,
 'jackpot': 4121,
 '81010': 737,
 'www': 8274,
 'dbuk': 2406,
 'net': 5163,
 'lccltd': 4415,
 'pobox': 5720,
 '4403ldnw1a7rw18': 559,
 'searching': 6495,
 'right': 6291,
 'words': 8219,
 'thank': 7404,
 'breather': 1643,
 'promise': 5926,
 'wont': 8209,
 'help': 3712,
 'granted': 3523,
 'fulfil': 3320,
 'wonderful': 8206,
 'blessing': 1521,
 'times': 7498,
 'date': 2394,
 'sunday': 7184,
 'xxxmobilemovieclub': 8293,
 'use': 7831,
 'credit': 2278,
 'click': 2023,
 'wap': 8010,
 'link': 4507,
 'message': 4857,
 'http': 3854,
 'com': 2089,
 'qjkgighjjgcbl': 6002,
 'oh': 5338,
 'watching': 8031,
 'eh': 2803,
 'remember': 6184,
 'spell': 6925,
 'yes': 8329,
 'did': 2532,
 'naughty': 5124,
 'make': 4716,
 'wet': 8106,
 'fine': 3128,
 'thatåõs': 7416,
 'way': 8043,
 'feel': 3076,
 'gota': 3495,
 'england': 2854,
 'macedonia': 4679,
 'dont': 2654,
 'miss': 4914,
 'goals': 3454,
 'team': 7335,
 'news': 5181,
 'ur': 7814,
 'national': 5118,
 '87077': 783,
 'try': 7665,
 'wales': 7985,
 'scotland': 6474,
 '4txt': 599,
 'ì¼1': 8391,
 'poboxox36504w45wq': 5732,
 'seriously': 6555,
 'going': 3463,
 'ha': 3595,
 'ì_': 8390,
 'pay': 5558,
 'da': 2359,
 'stock': 7053,
 'comin': 2100,
 'aft': 959,
 'finish': 3131,
 'lunch': 4645,
 'str': 7078,
 'lor': 4589,
 'ard': 1154,
 'smth': 6812,
 'ffffffffff': 3094,
 'alright': 1031,
 'meet': 4822,
 'sooner': 6865,
 'just': 4226,
 'forced': 3219,
 'eat': 2769,
 'slice': 6764,
 'really': 6098,
 'hungry': 3873,
 'tho': 7458,
 'sucks': 7153,
 'mark': 4752,
 'getting': 3413,
 'worried': 8230,
 'knows': 4323,
 'sick': 6685,
 'turn': 7688,
 'pizza': 5676,
 'lol': 4566,
 'convincing': 2199,
 'catch': 1845,
 'bus': 1723,
 'frying': 3308,
 'egg': 2800,
 'tea': 7329,
 'eating': 2772,
 'mom': 4972,
 'left': 4437,
 'dinner': 2564,
 'love': 4610,
 'amp': 1052,
 'packing': 5478,
 'car': 1807,
 'll': 4539,
 'let': 4457,
 'know': 4320,
 'room': 6332,
 'ahhh': 980,
 'work': 8220,
 'vaguely': 7854,
 'does': 2626,
 'wait': 7979,
 'clear': 2017,
 'sure': 7210,
 'sarcastic': 6430,
 'doesn': 2628,
 'live': 4531,
 'yeah': 8317,
 'apologetic': 1115,
 'fallen': 3030,
 'actin': 901,
 'spoilt': 6952,
 'child': 1956,
 'caught': 1849,
 'till': 7495,
 'doing': 2641,
 'badly': 1323,
 'cheers': 1932,
 'tell': 7353,
 'fear': 3068,
 'fainting': 3022,
 'housework': 3839,
 'quick': 6013,
 'cuppa': 2331,
 'thanks': 7405,
 'subscription': 7142,
 'ringtone': 6300,
 'uk': 7731,
 'charged': 1901,
 'month': 4988,
 'confirm': 2154,
 'replying': 6218,
 'yup': 8369,
 'look': 4577,
 'timings': 7502,
 'msg': 5026,
 'xuhui': 8288,
 'learn': 4428,
 '2nd': 461,
 'lesson': 4455,
 '8am': 809,
 'oops': 5382,
 'roommate': 6334,
 'letter': 4459,
 'decide': 2423,
 'hello': 3709,
 'saturday': 6442,
 'texting': 7396,
 'decided': 2424,
 'tomo': 7555,
 'trying': 7667,
 'invite': 4058,
 'pls': 5708,
 'ahead': 979,
 'watts': 8039,
 'wanted': 8007,
 'weekend': 8073,
 'abiola': 855,
 'forget': 3225,
 'need': 5144,
 'crave': 2268,
 'sweet': 7241,
 'arabian': 1151,
 'steed': 7035,
 'mmmmmm': 4941,
 'yummy': 8364,
 '07732584351': 30,
 'rodger': 6322,
 'burns': 1720,
 'tried': 7643,
 'sms': 6807,
 'nokia': 5225,
 'camcorder': 1782,
 '08000930705': 57,
 'delivery': 2463,
 'tomorrow': 7557,
 'seeing': 6513,
 'hope': 3807,
 'man': 4726,
 'endowed': 2844,
 'lt': 4633,
 'gt': 3563,
 'inches': 3972,
 'calls': 1777,
 'messages': 4859,
 'missed': 4916,
 'didn': 2534,
 'hep': 3723,
 'immunisation': 3953,
 'nigeria': 5194,
 'fair': 3023,
 'hopefully': 3810,
 'tyler': 7714,
 'maybe': 4798,
 'ask': 1203,
 'bit': 1498,
 'stubborn': 7106,
 'hospital': 3822,
 'kept': 4269,
 'telling': 7354,
 'weak': 8048,
 'sucker': 7151,
 'hospitals': 3823,
 'suckers': 7152,
 'thinked': 7444,
 'time': 7497,
 'saw': 6449,
 'class': 2009,
 'gram': 3515,
 'usually': 7843,
 'runs': 6375,
 'half': 3610,
 'eighth': 2805,
 'smarter': 6787,
 'gets': 3409,
 'second': 6499,
 'fyi': 3338,
 'ride': 6290,
 'morning': 4998,
 'crashing': 2267,
 'place': 5678,
 'wow': 8245,
 'realized': 6096,
 'embarassed': 2826,
 'accomodations': 884,
 'thought': 7461,
 'liked': 4486,
 'best': 1455,
 'happy': 3645,
 'cave': 1853,
 'sorry': 6874,
 'offered': 5324,
 'embarassing': 2827,
 'ac': 870,
 'sptv': 6974,
 'new': 5176,
 'jersey': 4162,
 'devils': 2513,
 'detroit': 2507,
 'red': 6138,
 'wings': 8155,
 'play': 5692,
 'ice': 3907,
 'hockey': 3774,
 'correct': 2216,
 'incorrect': 3983,
 'end': 2840,
 'mallika': 4725,
 'sherawat': 6612,
 'yesterday': 8331,
 'url': 7824,
 'congrats': 2160,
 'year': 8318,
 'special': 6912,
 'cinema': 1995,
 'pass': 5535,
 '09061209465': 219,
 'suprman': 7208,
 'matrix3': 4785,
 'starwars3': 7016,
 'bx420': 1743,
 'ip4': 4067,
 '5we': 641,
 '150pm': 353,
 'later': 4397,
 'meeting': 4824,
 'reached': 6080,
 'gauti': 3372,
 'sehwag': 6519,
 'odi': 5318,
 'series': 6554,
 'pick': 5648,
 'burger': 1715,
 'pain': 5485,
 'killing': 4294,
 'good': 3476,
 'joke': 4188,
 'girls': 3431,
 'situation': 6731,
 'seekers': 6514,
 'checking': 1926,
 'iq': 4073,
 'roommates': 6335,
 'took': 7570,
 'forever': 3222,
 'come': 2095,
 'double': 2668,
 'check': 1922,
 'hair': 3605,
 'dresser': 2697,
 'said': 6401,
 'wun': 8273,
 'cut': 2346,
 'short': 6647,
 'nice': 5188,
 'pleased': 5701,
 'advise': 942,
 'following': 3201,
 'recent': 6119,
 'review': 6277,
 'mob': 4949,
 'awarded': 1288,
 '1500': 350,
 'bonus': 1562,
 '09066364589': 267,
 'song': 6859,
 'dedicated': 2434,
 'dedicate': 2433,
 'valuable': 7860,
 'frnds': 3296,
 'rply': 6351,
 'complimentary': 2129,
 'trip': 7644,
 'eurodisinc': 2917,
 'trav': 7626,
 'aco': 898,
 'entry41': 2876,
 '1000': 299,
 'dis': 2576,
 '18': 368,
 'morefrmmob': 4995,
 'shracomorsglsuplt': 6670,
 '10': 297,
 'ls1': 4629,
 '3aj': 518,
 'hear': 3688,
 'divorce': 2605,
 'barbie': 1354,
 'comes': 2097,
 'ken': 4267,
 'plane': 5684,
 'wah': 7972,
 'lucky': 4639,
 'save': 6445,
 'money': 4979,
 'hee': 3701,
 'finished': 3133,
 'hi': 3737,
 'babe': 1310,
 'im': 3941,
 'wanna': 8003,
 'xx': 8289,
 'performed': 5594,
 'waiting': 7982,
 'machan': 4681,
 'thats': 7415,
 'cool': 2204,
 'gentleman': 3397,
 'dignity': 2554,
 'respect': 6244,
 'peoples': 5587,
 'shy': 6680,
 'pa': 5474,
 'operate': 5389,
 'looking': 4581,
 'job': 4177,
 'ta': 7268,
 'earn': 2758,
 'ah': 977,
 'stop': 7063,
 'urgnt': 7821,
 'real': 6089,
 'yo': 8340,
 'tickets': 7485,
 'jacket': 4120,
 'used': 7832,
 'multis': 5052,
 'started': 7011,
 'requests': 6225,
 'came': 1783,
 'bed': 1418,
 'coins': 2071,
 'factory': 3012,
 'gotta': 3500,
 'nitros': 5212,
 'ela': 2809,
 'kano': 4249,
 'il': 3936,
 'download': 2675,
 'wen': 8090,
 'stand': 6999,
 'close': 2030,
 'night': 5196,
 'spent': 6930,
 'late': 4394,
 'afternoon': 961,
 'casualty': 1843,
 'means': 4811,
 'haven': 3667,
 'stuff42moro': 7118,
 'includes': 3976,
 'sheets': 6607,
 'smile': 6795,
 'pleasure': 5703,
 'trouble': 7651,
 'pours': 5805,
 'rain': 6036,
 'sum1': 7175,
 'hurts': 3883,
 'becoz': 1416,
 'loves': 4618,
 'smiling': 6799,
 'service': 6558,
 'representative': 6222,
 '0800': 53,
 '169': 366,
 '6031': 647,
 '10am': 307,
 '9pm': 835,
 'guaranteed': 3566,
 '5000': 609,
 'havent': 3668,
 'planning': 5688,
 'buy': 1734,
 'lido': 4470,
 '530': 627,
 'collected': 2080,
 'simply': 6706,
 'password': 5542,
 'mix': 4932,
 '85069': 770,
 'verify': 7888,
 'usher': 7838,
 'britney': 1664,
 'fml': 3192,
 'telugu': 7359,
 'movie': 5015,
 'abt': 865,
 'loads': 4545,
 'loans': 4547,
 'wk': 8181,
 'hols': 3787,
 'run': 6373,
 'forgot': 3230,
 'hairdressers': 3607,
 'appointment': 1131,
 'shower': 6663,
 'cause': 1850,
 'prob': 5899,
 'ham': 3616,
 'okay': 5344,
 'price': 5875,
 'long': 4573,
 'legal': 4440,
 'ave': 1275,
 'ams': 1056,
 'gone': 3472,
 '4the': 597,
 'driving': 2706,
 'test': 7382,
 'mean': 4807,
 'guess': 3572,
 'gave': 3373,
 'boston': 1583,
 'men': 4843,
 'changed': 1891,
 'search': 6494,
 'location': 4550,
 'nyc': 5293,
 'cuz': 2353,
 'signin': 6694,
 'page': 5481,
 'says': 6453,
 'umma': 7738,
 'life': 4473,
 'vava': 7874,
 'lot': 4597,
 'dear': 2413,
 'wishes': 8168,
 'birthday': 1496,
 'making': 4720,
 'truly': 7660,
 'memorable': 4840,
 'aight': 987,
 'hit': 3754,
 'ip': 4066,
 'address': 919,
 'considering': 2172,
 'computer': 2135,
 'isn': 4090,
 'minecraft': 4892,
 'server': 6557,
 'grumpy': 3560,
 'old': 5356,
 'people': 5586,
 'better': 1461,
 'lying': 4659,
 'jokes': 4190,
 'worry': 8232,
 'busy': 1729,
 'plural': 5712,
 'noun': 5261,
 'research': 6230,
 'cos': 2221,
 'things': 7442,
 'scared': 6459,
 'mah': 4703,
 'loud': 4605,
 'gent': 3395,
 'contact': 2177,
 'weekends': 8074,
 'draw': 2689,
 'shows': 6669,
 '09064012160': 243,
 'k52': 4232,
 '12hrs': 333,
 '150ppm': 355,
 'wa': 7967,
 'openin': 5386,
 'sentence': 6547,
 'formal': 3234,
 'juz': 4231,
 'tt': 7675,
 'eatin': 2771,
 'puttin': 5991,
 'weight': 8079,
 'haha': 3601,
 'anythin': 1103,
 'happened': 3637,
 'entered': 2865,
 'cabin': 1751,
 'boss': 1582,
 'felt': 3085,
 'askd': 1204,
 'invited': 4059,
 'apartment': 1109,
 'went': 8093,
 'specially': 6916,
 'holiday': 3784,
 'flights': 3168,
 'operator': 5390,
 '0871277810910p': 129,
 'min': 4886,
 'goodo': 3485,
 'friday': 3283,
 'potato': 5797,
 'ratio': 6064,
 'tortilla': 7586,
 'needed': 5146,
 'hmm': 3766,
 'uncle': 7746,
 'informed': 4005,
 'paying': 5563,
 'school': 6465,
 'directly': 2570,
 'food': 3208,
 'private': 5891,
 '2004': 401,
 'account': 887,
 'statement': 7019,
 '07742676969': 32,
 '786': 709,
 'unredeemed': 7789,
 'points': 5742,
 '08719180248': 175,
 'identifier': 3919,
 '45239': 570,
 'expires': 2983,
 '2000': 399,
 'caller': 1770,
 '03': 15,
 'landline': 4372,
 '09064019788': 249,
 'box42wr29c': 1607,
 'apples': 1126,
 'pairs': 5489,
 'malarky': 4722,
 'todays': 7539,
 'voda': 7936,
 'numbers': 5279,
 'ending': 2842,
 '7548': 701,
 '350': 506,
 'award': 1287,
 'match': 4773,
 '08712300220': 111,
 'quoting': 6024,
 '4041': 543,
 'standard': 7000,
 'rates': 6063,
 'app': 1119,
 'sao': 6424,
 'mu': 5042,
 'ìï': 8393,
 'predict': 5837,
 'buying': 1737,
 'yetunde': 8333,
 'hasn': 3657,
 'sent': 6546,
 'bother': 1585,
 'sending': 6538,
 'involve': 4063,
 'shouldn': 6657,
 'imposed': 3960,
 'apologise': 1116,
 'girl': 3428,
 'del': 2453,
 'bak': 1331,
 'sum': 7174,
 'lucyxx': 4642,
 'tmorrow': 7525,
 'accomodate': 883,
 'answer': 1087,
 'sunshine': 7191,
 'quiz': 6020,
 'sony': 6861,
 'dvd': 2747,
 'player': 5694,
 'country': 2240,
 'algarve': 1015,
 'ansr': 1086,
 '82277': 744,
 'sp': 6897,
 'tyrone': 7718,
 'laid': 4364,
 'dogging': 2635,
 'locations': 4551,
 'direct': 2569,
 'join': 4185,
 'largest': 4389,
 'bt': 1690,
 'txting': 7707,
 'gravel': 3528,
 '69888': 675,
 'nt': 5269,
 'ec2a': 2774,
 '31p': 498,
 'haf': 3600,
 'msn': 5033,
 'yijue': 8337,
 'hotmail': 3830,
 'rooms': 6336,
 'befor': 1427,
 'activities': 907,
 'msgs': 5032,
 'chat': 1912,
 'svc': 7226,
 'hardcore': 3647,
 'services': 6559,
 '69988': 679,
 'age': 966,
 'yr': 8359,
 'lazy': 4414,
 'type': 7715,
 'lect': 4434,
 'pouch': 5800,
 'sir': 6720,
 'mail': 4708,
 'swt': 7255,
 'nver': 5287,
 'tired': 7505,
 'little': 4530,
 'lovable': 4609,
 'persons': 5611,
 'coz': 2253,
 'somtimes': 6856,
 'occupy': 5311,
 'biggest': 1479,
 'hearts': 3694,
 'gud': 3568,
 'ni8': 5186,
 'open': 5383,
 'ya': 8302,
 'dot': 2667,
 'whats': 8111,
 'staff': 6991,
 'taking': 7287,
 'replied': 6215,
 'randy': 6056,
 'sexy': 6574,
 'female': 3086,
 'local': 4549,
 'luv': 4650,
 'netcollex': 5164,
 '08700621170150p': 81,
 'ummma': 7740,
 'begin': 1431,
 'qatar': 5997,
 'pray': 5832,
 'hard': 3646,
 'deleted': 2457,
 'sindu': 6710,
 'birla': 1492,
 'soft': 6833,
 'wine': 8153,
 'flowing': 3183,
 'nevering': 5173,
 'thk': 7452,
 'plaza': 5699,
 'typical': 7717,
 'dirt': 2573,
 'floor': 3177,
 'windows': 8150,
 'shirt': 6626,
 'mouth': 5012,
 'dream': 2692,
 'chores': 1983,
 'joy': 4203,
 'lots': 4599,
 'tv': 7693,
 'exist': 2968,
 'hail': 3604,
 'mist': 4924,
 'aaooooright': 845,
 'leaving': 4433,
 'house': 3836,
 'interview': 4046,
 'boy': 1612,
 'missing': 4918,
 'annoncement': 1078,
 'years': 8319,
 '07046744435': 24,
 'arrange': 1180,
 '0871277810810': 128,
 'safe': 6396,
 'envy': 2881,
 'parents': 5518,
 'hand': 3619,
 'excited': 2956,
 'spend': 6928,
 'bootydelious': 1575,
 '32': 499,
 'inviting': 4060,
 'friend': 3287,
 '434': 556,
 'frnd': 3295,
 '62468': 655,
 'bangbabes': 1345,
 'order': 5411,
 'content': 2181,
 'goto': 3499,
 'bangb': 1344,
 'internet': 4045,
 'menu': 4850,
 'cultures': 2325,
 'module': 4965,
 '09061701939': 226,
 's89': 6386,
 'avoid': 1281,
 'missunderstding': 4922,
 'wit': 8173,
 'beloved': 1446,
 'escape': 2902,
 'fancy': 3041,
 'bridge': 1649,
 'needs': 5149,
 'lager': 4363,
 'completely': 2125,
 'form': 3233,
 'clark': 2006,
 'utter': 7845,
 'waste': 8023,
 'axis': 1296,
 'bank': 1347,
 'hmmm': 3767,
 'hop': 3806,
 'muz': 5076,
 'discuss': 2589,
 'liao': 4464,
 'coming': 2101,
 'bloody': 1535,
 'hell': 3707,
 'believe': 1437,
 'surname': 7216,
 'mr': 5021,
 'ill': 3938,
 'clue': 2046,
 'spanish': 6904,
 'begins': 1432,
 'bath': 1378,
 'carlos': 1824,
 'mall': 4724,
 'turns': 7691,
 'staying': 7026,
 'til': 7494,
 'smoke': 6801,
 'worth': 8236,
 'doesnt': 2629,
 'log': 4557,
 'spoke': 6953,
 'maneesha': 4736,
 'satisfied': 6439,
 'experience': 2978,
 'toll': 7551,
 'lifted': 4479,
 'hopes': 3812,
 'offer': 5323,
 'especially': 2906,
 'approaches': 1135,
 'studying': 7115,
 'anyways': 1106,
 'gr8': 3508,
 'trust': 7662,
 'guys': 3588,
 'bye': 1746,
 'handsome': 3625,
 'finding': 3126,
 'working': 8224,
 'mummy': 5056,
 'boytoy': 1617,
 'awesome': 1290,
 'minute': 4903,
 'freephone': 3273,
 '0808': 65,
 '145': 343,
 '4742': 574,
 '9am': 833,
 '11pm': 321,
 'xmas': 8285,
 'radio': 6029,
 'jus': 4225,
 'bathe': 1379,
 'sis': 6722,
 'using': 7839,
 'finishes': 3134,
 'unique': 7774,
 '30th': 494,
 'august': 1257,
 'areyouunique': 1160,
 'joined': 4186,
 'league': 4426,
 'touch': 7595,
 'deal': 2409,
 'personal': 5608,
 'finally': 3123,
 'completed': 2124,
 'course': 2246,
 'suggest': 7166,
 'stays': 7027,
 'able': 857,
 'ors': 5424,
 'stool': 7062,
 'settled': 6566,
 'wishin': 8169,
 'mrng': 5023,
 'hav': 3665,
 'story': 7077,
 'hamster': 3618,
 'dead': 2408,
 'tmr': 7526,
 '1pm': 385,
 'orchard': 5410,
 'mrt': 5024,
 'kate': 4254,
 'evening': 2923,
 ...}

In [89]:
print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['00' '000' '000pes' ... 'ûïharry' 'ûò' 'ûówell']
8404

In [96]:
#X_transformed=vec.transform(X)
#X_transformed
X_transformed = vec.transform([str(x) for x in X])

In [97]:
X=X_transformed.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [98]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,ó_,û_,û_thanks,ûªm,ûªt,ûªve,ûï,ûïharry,ûò,ûówell
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
df2 = pd.read_csv('spam.csv',encoding='latin#1')
df2

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [102]:
#test_numpy_array = df2.values
#X_test = test_numpy_array[:, 0]
#y_test = test_numpy_array[:, 1]
#y_test = y_test.astype('int')
#print("X_test:", X_test)
#print("y_test:", y_test)
unique_values = np.unique(y_test)
print(unique_values)

[' &lt;#&gt;  in mca. But not conform.'
 ' &lt;#&gt;  mins but i had to stop somewhere first.'
 ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla'
 ... 'ÌÏ thk of wat to eat tonight.' 'ÌÏ v ma fan...'
 'ÌÏ wait 4 me in sch i finish ard 5..']

In [103]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<5572x8404 sparse matrix of type '<class 'numpy.int64'>'
	with 5572 stored elements in Compressed Sparse Row format>

In [104]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [105]:
mnb=MultinomialNB()

mnb.fit(X,Y)

mnb.predict_proba(X_test)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [107]:
y_prediction = mnb.predict(X_test)


acc = accuracy_score(y_test, y_prediction)


print("Accuracy:", acc)

Accuracy: 0.0